In [ ]:
import sqlite3
import pandas as pd
import os

# File paths
csv_file = "processed_data.csv"  # Path to your CSV file
sqlite_file = "output/imdb_movies.db"  # Path to the SQLite file to be created

# Create the output directory if it doesn't exist
os.makedirs(os.path.dirname(sqlite_file), exist_ok=True)

# Table name
table_name = "movies"

try:
    # Load the CSV file into a Pandas DataFrame
    df = pd.read_csv(csv_file)
    
    # Connect to SQLite database (it will create the file if it doesn't exist)
    conn = sqlite3.connect(sqlite_file)
    print("Connected to SQLite database.")
    
    # Write the DataFrame to an SQLite table
    df.to_sql(table_name, conn, if_exists='replace', index=False)
    print(f"Data successfully written to SQLite database in the table '{table_name}'.")
    
except Exception as e:
    print(f"An error occurred: {e}")

Connected to SQLite database.
Data successfully written to SQLite database in the table 'movies'.
SQLite database connection closed.

In [4]:
df.head()

,id,title,year,rating,votes,budget,gross_world_wide,gross_us_canada,opening_weekend_gross,genres,production_companies,wins,nominations,oscars
0,tt1502397,Bad Boys for Life,2020,6.5,187K,90000000.0,426505244.0,206305244.0,62504105.0,"['Buddy Cop', 'Cop Drama', 'Action', 'Comedy',...","['Columbia Pictures', '2.0 Entertainment', 'Do...",0,15,0
1,tt8332922,A Quiet Place Part II,2020,7.2,296K,61000000.0,297372261.0,160072261.0,47547231.0,"['Alien Invasion', 'Monster Horror', 'Supernat...","['Paramount Pictures', 'Platinum Dunes', 'Sund...",0,44,1
2,tt3794354,Sonic the Hedgehog,2020,6.5,171K,85000000.0,319715683.0,148974665.0,58018348.0,"['Animal Adventure', 'Buddy Comedy', 'Road Tri...","['Paramount Pictures', 'Sega Sammy Group', 'Or...",0,12,0
3,tt7713068,Birds of Prey and the Fantabulous Emancipation...,2020,6.1,271K,84500000.0,205537933.0,84172791.0,33010017.0,"['Dark Comedy', 'Superhero', 'Action', 'Comedy...","['Clubhouse Pictures (II)', 'DC Entertainment'...",0,83,0
4,tt6673612,Dolittle,2020,5.6,73K,175000000.0,251410631.0,77047065.0,21844045.0,"['Animal Adventure', 'Quest', 'Adventure', 'Co...","['Universal Pictures', 'Perfect World Pictures...",0,9,0

In [ ]:
   # Close the connection
    conn.close()
    print("SQLite database connection closed.")